# Generated by Django 5.0.8 on 2024-08-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interpolApp", "0002_notice_sex_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="arrest_warrants",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="country_of_birth_id",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="distinguishing_marks",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="eyes_colors_id",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="hairs_id",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="languages_spoken_ids",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="place_of_birth",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="weight",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notice",
            name="sex_id",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
