# Generated by Django 5.0.7 on 2024-08-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "interpolApp",
            "0003_notice_arrest_warrants_notice_country_of_birth_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="created",
            field=models.BooleanField(default=False),
        ),
    ]
